language: php
php:
  - '7.0'
  - nightly

before_script:
  - composer require satooshi/php-coveralls:dev-master
  - composer install && composer dump-autoload -o

script:
  - ./vendor/bin/phpunit --coverage-clover ./clover.xml

after_script:
  - php